#!/usr/bin/env bash
set -euo pipefail

PERF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
export PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${PERF_DIR}/.." && pwd)}"
export PERF_PP_VPP_ROOT="${PERF_PP_VPP_ROOT:-${PROJECT_ROOT}/perf_pp_vpp}"
export MEGATRON_ROOT="${MEGATRON_ROOT:-${PROJECT_ROOT}}"
export PYTHON_BIN="${PYTHON_BIN:-python}"
export TORCHRUN_BIN="${TORCHRUN_BIN:-torchrun}"
export NSYS_BIN="${NSYS_BIN:-nsys}"
export NCCL_TESTS_ROOT="${NCCL_TESTS_ROOT:-}"
export MASTER_ADDR="${MASTER_ADDR:-chenny-dist-0.chenny-dist.default.svc.sspu.local}"
export MASTER_PORT="${MASTER_PORT:-29500}"
export NNODES="${NNODES:-2}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-8}"
export NODE_RANK="${NODE_RANK:-0}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export OUTPUT_ROOT="${OUTPUT_ROOT:-${PERF_PP_VPP_ROOT}/outputs}"
export DATA_ROOT="${DATA_ROOT:-${OUTPUT_ROOT}/data}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-/workspace/models/qwen3-14B}"
export CHECKPOINT_ROOT="${CHECKPOINT_ROOT:-${OUTPUT_ROOT}/checkpoints}"
export MODEL_SOURCE_PATH_QWEN3_14B="${MODEL_SOURCE_PATH_QWEN3_14B:-/workspace/models/qwen3-14B}"
export MODEL_SOURCE_PATH_QWEN3_32B="${MODEL_SOURCE_PATH_QWEN3_32B:-/workspace/models/qwen3-32B}"

export KUBECTL_BIN="${KUBECTL_BIN:-kubectl}"
export K8S_NAMESPACE="${K8S_NAMESPACE:-default}"
export NODE0_POD="${NODE0_POD:-chenny-dist-0}"
export NODE1_POD="${NODE1_POD:-chenny-dist-1}"
export REMOTE_PROJECT_ROOT="${REMOTE_PROJECT_ROOT:-/workspace/code/Megatron-LM}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-net1}"
export PERF_SEED="${PERF_SEED:-1234}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-1}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"

mkdir -p "${OUTPUT_ROOT}" "${DATA_ROOT}" "${CHECKPOINT_ROOT}"
